// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9VWTPW1DVa1_VxJtq-n0OcRnAADXiTjI',
    appId: '1:868112014509:web:a0aeb3dc29f30818bd3a24',
    messagingSenderId: '868112014509',
    projectId: 'space-app-84052',
    authDomain: 'space-app-84052.firebaseapp.com',
    storageBucket: 'space-app-84052.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkKRnR4GLQa3svUx4aS4-fepEKUqsgopU',
    appId: '1:868112014509:android:e13e2b8a58d8fe3bbd3a24',
    messagingSenderId: '868112014509',
    projectId: 'space-app-84052',
    storageBucket: 'space-app-84052.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWPrT4wyq4TPEsjPAktcRYludxw161ZhU',
    appId: '1:868112014509:ios:0fbd6aaba04fc728bd3a24',
    messagingSenderId: '868112014509',
    projectId: 'space-app-84052',
    storageBucket: 'space-app-84052.appspot.com',
    iosBundleId: 'com.example.spaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWPrT4wyq4TPEsjPAktcRYludxw161ZhU',
    appId: '1:868112014509:ios:1fef3bea2949bda0bd3a24',
    messagingSenderId: '868112014509',
    projectId: 'space-app-84052',
    storageBucket: 'space-app-84052.appspot.com',
    iosBundleId: 'com.example.spaceApp.RunnerTests',
  );
}
